### ISSUE TITLE
Problem installing on macOS: Command `git rev-parse HEAD` failed with code 128: fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by ralfr** [h2oai/datatable#2901] opened 2021-03-17 15:54 UTC
Trying to install datatable (Python 3.9.0 / pip 21.0.1 / macOS 11.2.3 Intel) I run into the following error log:

``python --version
Python 3.9.0``

``pip --version
pip 21.0.1 from /Users/ralfr/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pip (python 3.9)``

``pip install datatable``

``Collecting datatable
  Using cached datatable-0.11.1.tar.gz (1.0 MB)
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ralfr/.pyenv/versions/3.9.0/bin/python3.9 /Users/ralfr/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/tmp7j2roqoa
         cwd: /private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-install-sk5hrpp3/datatable_0b6d44a2769346fa893ef9e14d21da82
    Complete output (2 lines):
    Command `git rev-parse HEAD` failed with code 128: fatal: not a git repository (or any of the parent directories): .git

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6a/4c/22f3be0cb1be3caaa737abd2d84dc98ebd9de45eb0cf15eb45f96c7690a7/datatable-0.11.1.tar.gz#sha256=3c3a7d3bee3c463a36fe77c5d4747278a741c23fc6c6e2dba110deec200502ba (from https://pypi.org/simple/datatable/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/ralfr/.pyenv/versions/3.9.0/bin/python3.9 /Users/ralfr/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/tmp7j2roqoa Check the logs for full command output.
  Using cached datatable-0.11.0.tar.gz (1.0 MB)
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ralfr/.pyenv/versions/3.9.0/bin/python3.9 /Users/ralfr/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/tmpepldnww7
         cwd: /private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-install-sk5hrpp3/datatable_1a755abcfe2c40419c2f4953174d3611
    Complete output (2 lines):
    Command `git rev-parse HEAD` failed with code 128: fatal: not a git repository (or any of the parent directories): .git

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2e/6a/bba91ebcff851f7b650ddcf2783b997c7f9b4c2d46f7c90bd7e436396f99/datatable-0.11.0.tar.gz#sha256=19c602711e00f72e9ae296d8fa742d46da037c2d3a2d254bdf68f817a8da76bb (from https://pypi.org/simple/datatable/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/ralfr/.pyenv/versions/3.9.0/bin/python3.9 /Users/ralfr/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/tmpepldnww7 Check the logs for full command output.
  Using cached datatable-0.10.1.tar.gz (893 kB)
Requirement already satisfied: typesentry>=0.2.6 in /Users/ralfr/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from datatable) (0.2.7)
Requirement already satisfied: blessed in /Users/ralfr/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from datatable) (1.18.0)
Requirement already satisfied: colorama>=0.3 in /Users/ralfr/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from typesentry>=0.2.6->datatable) (0.4.4)
Requirement already satisfied: six>=1.9.0 in /Users/ralfr/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from blessed->datatable) (1.15.0)
Requirement already satisfied: wcwidth>=0.1.4 in /Users/ralfr/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from blessed->datatable) (0.2.5)
Building wheels for collected packages: datatable
  Building wheel for datatable (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ralfr/.pyenv/versions/3.9.0/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-install-sk5hrpp3/datatable_9101daaedbb74bc4a78a81f8a88ea174/setup.py'"'"'; __file__='"'"'/private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-install-sk5hrpp3/datatable_9101daaedbb74bc4a78a81f8a88ea174/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-wheel-girw2gis
       cwd: /private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-install-sk5hrpp3/datatable_9101daaedbb74bc4a78a81f8a88ea174/
  Complete output (77 lines):

  Start setup.py
    command = `bdist_wheel`
    setuptools version = 49.2.1

  Find an LLVM installation
    Environment variable LLVM is not set
    Environment variable LLVM7 is not set
    Environment variable LLVM6 is not set
    Environment variable LLVM5 is not set
    Environment variable LLVM4 is not set
    Candidate directory `/usr/local/opt/llvm` not found
    The build will proceed without Llvm support

  Determine the compiler
    Environment variable `CXX` is not set
    Environment variable `CC` is not set
    Llvm installation not found, cannot search for the clang++ compiler
    distutils.ccompiler reports the default compiler to be `cc`
    Compiler `clang++` will be used
    clang++ --version :
      Apple clang version 12.0.0 (clang-1200.0.32.29)
      Target: x86_64-apple-darwin20.3.0
      Thread model: posix
      InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

  Prepare the environment
    CC = clang++
    CXX = clang++
    LDFLAGS =
    ARCHFLAGS = -m64
    LLVM_CONFIG =
    MACOSX_DEPLOYMENT_TARGET = 10.13

  Find compile include directories
    `c` is the main C++ source directory
    `/Users/ralfr/.pyenv/versions/3.9.0/include/python3.9` added from CONFINCLUDEPY

  Determine the extra compiler flags
    -std=c++11
    -stdlib=libc++
    -Ic
    -fPIC
    -g2
    -O3
    -Weverything
    -Wno-c++98-compat-pedantic
    -Wno-c99-extensions
    -Wno-exit-time-destructors
    -Wno-float-equal
    -Wno-global-constructors
    -Wno-reserved-id-macro
    -Wno-switch-enum
    -Wno-weak-template-vtables
    -Wno-weak-vtables
    -Ic
    -I/Users/ralfr/.pyenv/versions/3.9.0/include/python3.9
    -isystem /Users/ralfr/.pyenv/versions/3.9.0/include/python3.9

  libc++.1.dylib :::: 1 ::::
  Find the required dynamic libraries

  Determine the extra linker flags

  SystemExit: `locate` command returned the following error while looking for libc++.1.dylib:

  WARNING: The locate database (/var/db/locate.database) does not exist.
  To create the database, run the following command:

    sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

  Please be aware that the database can take some time to generate; once
  the database has been created, this message will no longer appear.

  ----------------------------------------
  ERROR: Failed building wheel for datatable
  Running setup.py clean for datatable
Failed to build datatable
Installing collected packages: datatable
    Running setup.py install for datatable ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ralfr/.pyenv/versions/3.9.0/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-install-sk5hrpp3/datatable_9101daaedbb74bc4a78a81f8a88ea174/setup.py'"'"'; __file__='"'"'/private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-install-sk5hrpp3/datatable_9101daaedbb74bc4a78a81f8a88ea174/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-record-mki_j_zw/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ralfr/.pyenv/versions/3.9.0/include/python3.9/datatable
         cwd: /private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-install-sk5hrpp3/datatable_9101daaedbb74bc4a78a81f8a88ea174/
    Complete output (77 lines):

    Start setup.py
      command = `install`
      setuptools version = 49.2.1

    Find an LLVM installation
      Environment variable LLVM is not set
      Environment variable LLVM7 is not set
      Environment variable LLVM6 is not set
      Environment variable LLVM5 is not set
      Environment variable LLVM4 is not set
      Candidate directory `/usr/local/opt/llvm` not found
      The build will proceed without Llvm support

    Determine the compiler
      Environment variable `CXX` is not set
      Environment variable `CC` is not set
      Llvm installation not found, cannot search for the clang++ compiler
      distutils.ccompiler reports the default compiler to be `cc`
      Compiler `clang++` will be used
      clang++ --version :
        Apple clang version 12.0.0 (clang-1200.0.32.29)
        Target: x86_64-apple-darwin20.3.0
        Thread model: posix
        InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

    Prepare the environment
      CC = clang++
      CXX = clang++
      LDFLAGS =
      ARCHFLAGS = -m64
      LLVM_CONFIG =
      MACOSX_DEPLOYMENT_TARGET = 10.13

    Find compile include directories
      `c` is the main C++ source directory
      `/Users/ralfr/.pyenv/versions/3.9.0/include/python3.9` added from CONFINCLUDEPY

    Determine the extra compiler flags
      -std=c++11
      -stdlib=libc++
      -Ic
      -fPIC
      -g2
      -O3
      -Weverything
      -Wno-c++98-compat-pedantic
      -Wno-c99-extensions
      -Wno-exit-time-destructors
      -Wno-float-equal
      -Wno-global-constructors
      -Wno-reserved-id-macro
      -Wno-switch-enum
      -Wno-weak-template-vtables
      -Wno-weak-vtables
      -I/Users/ralfr/.pyenv/versions/3.9.0/include/python3.9
      -isystem /Users/ralfr/.pyenv/versions/3.9.0/include/python3.9
      -Ic

    libc++.1.dylib :::: 1 ::::
    Find the required dynamic libraries

    Determine the extra linker flags

    SystemExit: `locate` command returned the following error while looking for libc++.1.dylib:

    WARNING: The locate database (/var/db/locate.database) does not exist.
    To create the database, run the following command:

      sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

    Please be aware that the database can take some time to generate; once
    the database has been created, this message will no longer appear.

    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ralfr/.pyenv/versions/3.9.0/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-install-sk5hrpp3/datatable_9101daaedbb74bc4a78a81f8a88ea174/setup.py'"'"'; __file__='"'"'/private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-install-sk5hrpp3/datatable_9101daaedbb74bc4a78a81f8a88ea174/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/68/p0zcd6997tn01bs1d71q4pjc0000gn/T/pip-record-mki_j_zw/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ralfr/.pyenv/versions/3.9.0/include/python3.9/datatable Check the logs for full command output.``

**Comment by st-pasha** [comment] 2021-03-17 16:31
Thanks for the report, however this issue is a duplicate of #2846.

**Closed by st-pasha** 2021-03-17 16:31 UTC
