### ISSUE TITLE
double negate a column of string

### ISSUE THREAD

**Issue by pradkrish** [h2oai/datatable#2616] opened 2020-09-14 22:57 UTC
Running the following 
```python
from datatable import dt, f

DT = dt.Frame(x=['adferg', 'reneeas', 'ldodls', 'qu', 'zleuss', 'ni'])
DT[:, :, dt.sort(-(-f.x))]
```
gives `TypeError: Cannot apply unary operator - to a column with stype str32`. It works if the column is of type int or float. isn't this a bug?

**Comment by st-pasha** [comment] 2020-09-15 00:03
No, this is not a bug. If `"zleuss"` is a string (of type `str`), then `-"zleuss"` is not a valid entity (unless you're willing to create a special type `negated_str` and define which operations should be valid for it). As such, if `f.x` is a string column then `-f.x` is not valid, and therefore `--f.x` is not valid either.

But if so, how can we sort by `-f.x` then? This is because there is a special logic that internally converts `sort(-f.x)` into the equivalent of `sort(f.x, reverse=True)` (regardless of the type of column `x`). In theory that logic can be extended to make it recursive, so that `sort(--f.x)` would mean the same as `sort(f.x)`, but I just can't see how this could be useful...

**Comment by pradkrish** [comment] 2020-09-15 12:21
I agree that it doesn't make sense for strings. My intention was to bring into notice the API inconsistency, that is, the equivalence of `DT[:, :, dt.sort(-f.x, reverse=True)]` and `DT[:, :, dt.sort(-(-f.x))]` holds true for all types except str.

**Comment by st-pasha** [comment] 2020-09-16 00:26
I don't think there is anything else to do w.r.t. this issue, so closing.

**Closed by st-pasha** 2020-09-16 00:26 UTC
Labels: question
