### ISSUE TITLE
to_csv() writes incorrect value

### ISSUE THREAD

**Issue by nkalonia1** [h2oai/datatable#1974] opened 2019-08-23 21:26 UTC
It seems like `to_csv()` writes an incorrect value for certain cases of float64s

```
>>> a = np.array([np.float64(0.33444187564173977)])
>>> a[0]
0.33444187564173977
>>> df = dt.Frame(a)
>>> df[0,0]
0.33444187564173977
>>> df.to_csv("tmp.csv")
>>> df2 = dt.fread("tmp.csv")
>>> df2[0,0]
0.3344418756417398
>>> df[0,0] == df2[0,0]
False
```
An inspection of `tmp.csv` shows that the value was written as `0.3344418756417398`, so it's not a `fread()` issue.

Using datatable version `0.8.0`

**Comment by st-pasha** [comment] 2019-08-23 22:24
Duplicate of #1868

**Closed by st-pasha** 2019-08-23 22:24 UTC
Labels: bug
