### ISSUE TITLE
Cannot parse airline sentiment dataset

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/datatable#2074] opened 2019-10-10 16:25 UTC
* Tried to parse the airlines sentiment dataset from https://www.figure-eight.com/wp-content/uploads/2016/03/Airline-Sentiment-2-w-AA.csv but got the following:

```
In [3]: dt.fread("Airline-Sentiment-2-w-AA.csv")                                                                                                                                    
100% |ââââââââââââââââââââââââââââââââââââââââââââââââââ| (error) data
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-046e05c26643> in <module>
----> 1 dt.fread("Airline-Sentiment-2-w-AA.csv")

~/h2oai/env/lib/python3.6/site-packages/datatable/fread.py in fread(anysource, file, text, cmd, url, columns, sep, dec, max_nrows, header, na_strings, verbose, fill, encoding, skip_to_string, skip_to_line, skip_blank_lines, strip_whitespace, quotechar, save_to, nthreads, logger, **extra)
     62     del params["extra"]
     63     freader = GenericReader(**params)
---> 64     return freader.read()
     65 
     66 

~/h2oai/env/lib/python3.6/site-packages/datatable/fread.py in read(self)
    676                 return res
    677             else:
--> 678                 return core.gread(self)
    679         finally:
    680             self._clear_temporary_files()

RuntimeError: Too few fields on line 1: expected 3 but found only 2 (with sep=';'). Set fill=True to ignore this error.  <<_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,airline_sentiment,airline_sentiment:confidence,negativereason,negativereason:confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone\r681448150,FALSE,finalized,3,2/25/15 5:24,neutral,1,,,Virgin America,,cairdin,,0,@VirginAmerica What @dhepburn said.,,2/24/15 11:35,5.70306E+17,,Eastern Time (US & Canada)\r681448153,FALSE,finalized,3,2/2...>>
```

**Comment by st-pasha** [comment] 2019-10-10 17:35
Duplicate of #1343

**Comment by joby-h20** [comment] 2019-11-07 17:57
discovered in the test for 1.8.1 release too.

**Closed** 2020-05-14 19:30 UTC
Labels: bug, duplicate, fread
