### ISSUE TITLE
datatable.median() RuntimeError: Invalid data access for a virtual column

### ISSUE THREAD

**Issue by shanemcandrewai** [h2oai/datatable#2848] opened 2021-02-10 17:11 UTC
- Did you find a bug in datatable, or maybe the bug found you?
  Tell us what it is.

For the example below, datatable.median() fails with RuntimeError: Invalid data access for a virtual column

- How to reproduce the bug?
  **This part is the most important**. Please provide a code snippet which, when
  executed in console, demonstrates the problem. If necessary, attach any data
  files to the issue.

Save [this CSV](https://www.kaggle.com/c/jane-street-market-prediction/data?select=train.csv) in directory `jane-street-market-prediction`

```
import datatable as dt
DT = dt.fread('jane-street-market-prediction/train.csv')
DT[:, dt.mean(dt.f.feature_27), dt.by(dt.f.date)] #works OK
DT[:, dt.sd(dt.f.feature_27), dt.by(dt.f.date)] # works OK
DT[:, dt.median(dt.f.feature_27), dt.by(dt.f.date)] #fails with error -

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-40-b21544b41271> in <module>
----> 1 DT[:, dt.median(dt.f.feature_27), dt.by(dt.f.date)]

RuntimeError: Invalid data access for a virtual column

```

- What was the expected behavior?

return a table of median values grouped by date

  In case it is not obvious, please tell us what result should your code
  produce.

- Your environment?
  What is your datatable version, python version, and operating system?

!pip show datatable

Name: datatable
Version: 0.11.1
Pythons 3.8
Windows 10

- Tag the issue with `[bug]` or `[segfault]` (depending on whether it crashes
  Python or not).

[bug]
- Thank you for contributing, and sorry for the inconvenience.

**Comment by shanemcandrewai** [comment] 2021-02-10 21:40
I found a work-around for this problem which might provide clue to the root cause -
```
import datatable as dt
DT = dt.fread('jane-street-market-prediction/train.csv', columns={'date', 'feature_27'})
DT.to_jay("date_f_27.jay")
DT2 = dt.fread("date_f_27.jay")
DT2[:, dt.median(dt.f.feature_27), dt.by(dt.f.date)] #works ok
```
[date_f_27.zip](https://github.com/h2oai/datatable/files/5961670/date_f_27.zip)

**Comment by st-pasha** [comment] 2021-02-11 21:41
Thanks for the detailed report. 
I was able to reproduce the bug on macOS-py3.7-dt0.11, however not on the latest dev version of datatable. This could indicate that this problem was already resolved. I'll try to dig some more into the possible roots here.

Btw, instead of saving/opening the data to Jay, you could also run `DT.materialize()` after fread.

**Comment by st-pasha** [comment] 2021-03-25 00:32
Closing, since there is nothing to fix here.

**Closed by st-pasha** 2021-03-25 00:32 UTC
Labels: bug
