### ISSUE TITLE
Does `datatable`  support  `isin`?

### ISSUE THREAD

**Issue by nankaimy** [h2oai/datatable#3358] opened 2022-09-26 10:13 UTC
does it  support  isin?

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html

Missing functionality
Listed below are some functions in pandas that do not have an equivalent in datatable yet, and are likely to be implemented:

Reshaping functions

[melt](https://pandas.pydata.org/docs/reference/api/pandas.melt.html)

[wide_to_long](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.wide_to_long.html)

[pivot_table](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html)

Convenience function for filtering and subsetting

[isin](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html)

[Datetime functions](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html)

Missing values

[forward fill](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ffill.html)

[backward fill](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.bfill.html)

Aggregation functions, such as

[expanding](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.expanding.html)

[rolling](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rolling.html)

String functions, such as

[string split](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.split.html)

[string extract](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.str.extract.html)

[string replace](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.replace.html)

Custom function application, via [pd.apply](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html) and [pd.pipe](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pipe.html).

If there are any functions that you would like to see in datatable, please head over to [github](https://github.com/h2oai/datatable/issues) and raise a feature request.

**Comment by oleksiyskononenko** [comment] 2022-09-26 19:54
Duplicate of #699

**Closed by oleksiyskononenko** 2022-09-26 19:54 UTC
Labels: question
