### ISSUE TITLE
missing import sys!

### ISSUE THREAD

**Issue by psulski** [h2oai/datatable#3384] opened 2022-11-16 15:51 UTC
Hello guys, 
look on the output:

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/*/*/*/*/*/lib/python3.8/site-packages/datatable/utils/fread.py", line 156, in _resolve_source_file
    if sys.platform == "win32":
NameError: name 'sys' is not defined

**Comment by oleksiyskononenko** [comment] 2022-11-16 19:12
Duplicate of https://github.com/h2oai/datatable/issues/3178

**Closed by oleksiyskononenko** 2022-11-16 19:12 UTC
