### ISSUE TITLE
[bug] datatable breaks conda commands

### ISSUE THREAD

**Issue by eedokl** [h2oai/datatable#2796] opened 2020-12-07 09:34 UTC
- Did you find a bug in datatable, or maybe the bug found you?
I have a problem when I pip install datatable to my conda based windows environment.
Datatable as such works perfectly. However, once installed my conda commands like conda list or conda env export are not working anymore - and it seems related to a SHA256 checksum performed on the License file in the datatable package.

- How to reproduce the bug?

after pip install datatable run "conda list"
Debug trace:
...
File "C:\Program Files\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 269, in get_paths
records = process_csv_row(record_reader)
File "C:\Program Files\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 249, in process_csv_row
cleaned_path, checksum)
AssertionError: ('C:\Users\xyz\.conda\envs\debug\Lib\site-packages\datatable-0.11.0.dist-info', 'Lib/site-packages/datatable-0.11.0.dist-info/LICENSE', 'HyVuytGSiAUQ6ErWBHTqt1iSGHhLmlC8fO7jTCuR8dU')

- What was the expected behavior?
  In case it is not obvious, please tell us what result should your code
  produce.

- Your environment?
  What is your datatable version, python version, and operating system?
0.11.0, Python 3.7.9, Windows 10 64 bit
          conda version : 4.7.12
    conda-build version : 3.18.8

**Comment by st-pasha** [comment] 2020-12-07 17:51
Duplicate of #2746. The fix is already available, and will be released in 0.11.1 very  soon.

**Closed by st-pasha** 2020-12-07 17:51 UTC
