### ISSUE TITLE
dt.isna gives segfault on big file after join

### ISSUE THREAD

**Issue by goldentom42** [h2oai/datatable#2049] opened 2019-10-01 15:31 UTC
Using the airline dataset and trying to augment it with airports data.
After the join I'm trying to count the number of NaNs to see what airports are missing airports.
Doing this operation issues a `segmentation fault` but on one specific column.

Here is the data I use :
 - Airline data (15GB)
 https://s3.amazonaws.com/h2o-airlines-unpacked/allyears.1987.2013.csv

 - Airport dataset attached here :  
[airport-codes_csv.csv.zip](https://github.com/h2oai/datatable/files/3677098/airport-codes_csv.csv.zip)

- How to reproduce the bug?

Here is my script:
```
import datatable as dt

train = dt.fread('allyears.1987.2013.csv')

all_airports = dt.fread('airport-codes_csv.csv.zip')

print(all_airports['coordinates'])

selected_feats = ['iata_code', 'elevation_ft', 'iso_country', 'coordinates']
origin_airports = all_airports[:, selected_feats]
origin_airports.names = ['Origin' if f == 'iata_code' else f+'_origin' for f in selected_feats]
origin_airports = origin_airports[dt.f['Origin']!='', :]
origin_airports = origin_airports[dt.f['Origin']!='0', :]
origin_airports = origin_airports[dt.f['Origin']!='-', :]

# Drop duplicates
origin_airports = origin_airports[:1, :, dt.by('Origin')]

print(origin_airports[:, dt.isna(dt.f['iso_country_origin'])].sum1())
print(origin_airports[:, dt.isna(dt.f['elevation_ft_origin'])].sum1())
print(origin_airports[:, dt.isna(dt.f['coordinates_origin'])].sum1())

origin_airports.key = 'Origin'
quick_merge = train[:, 'Origin'][:, :, dt.join(origin_airports)]

print(quick_merge.names)
print(quick_merge.ltypes)

print(quick_merge[:, dt.isna(dt.f['elevation_ft_origin'])].sum1())

print(quick_merge[:, dt.isna(dt.f['iso_country_origin'])].sum1())

print(dt.unique(quick_merge[dt.isna(dt.f['iso_country_origin']), 'Origin']))

print(dt.unique(quick_merge[dt.isna(dt.f['elevation_ft_origin']), 'Origin']))

print(dt.unique(quick_merge[dt.isna(dt.f['coordinates_origin']), 'Origin']))

print(quick_merge[:, dt.isna(dt.f['coordinates_origin'])].sum1())
```

- What was the expected behavior?
I was expecting datatable to give me a number :) 

- Your environment?
 I'm using python 3.7 (conda),  datatable 0.9.0 and  ubuntu 16.04LTS

Thx for your help

**Comment by st-pasha** [comment] 2019-10-01 18:45
I could not reproduce the crash on the latest dev version of datatable, will try to see whether it works on 0.9.0 or not.

**Comment by st-pasha** [comment] 2019-10-01 22:38
Confirm that it crashes on 0.9.
Bisecting shows that this issue was resolved in #2035

**Comment by st-pasha** [comment] 2019-10-01 23:32
After digging some more, it appears the problem is not with `isna()` function, but rather with materializing a string column. In particular, the column breaks str32 barrier, and this case wasn't handled properly.

I'm going to close the issue, considering that its reasons are now well understood, and that it has already been fixed.

**Closed by st-pasha** 2019-10-01 23:32 UTC
Labels: segfault

**Comment by goldentom42** [comment] 2019-10-02 06:37
Thx @st-pasha so I assume my only option is to pull dev and build, right ?

**Comment by st-pasha** [comment] 2019-10-02 19:01
@goldentom42 Yes, you can either build manually (`pip install git+https://github.com/h2oai/datatable`), or take one of the master builds from Jenkins (http://mr-0xc1:8080/job/h2o-py-data-table/job/master/).
