### ISSUE TITLE
[bug] fread cannot read 5GB csv on Windows

### ISSUE THREAD

**Issue by pstoyanov** [h2oai/datatable#2767] opened 2020-11-24 17:09 UTC
Hi, I ran into a strange issue with `datatable.fread()` on Windows 10 (64-bit) and thought to report it.

__Problem:__ Cannot open a 5GB text file on Windows. Does not matter if I try to read the whole file, or just one or two columns.

Sample code:
``` python
import datatable as dt
filename = "datafile.txt"
DT = dt.fread(file=filename, verbose=True)
```

Throws the following error:
```
[*] Process input parameters
  Using default 8 thread(s)
  na_strings = ["NA"]
  strip_whitespace = True
  skip_blank_lines = False
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
00.EDA.py in 
----> 32 DT = dt.fread(file=filename, verbose=True)

IOError: Unable to obtain size of datafile.txt: [errno 132] value too large
```

I cannot share the file (proprietary data) but :
(a) I can open the same file on the same machine using R's `fread()`
(b) I can open the same file on a Linux machine with the same version of `datatable` (python 3.6 though)

Tried two 64-bit python versions (Anaconda 3.7 + 3.8 distribution as from the Windows store).
This is on Windows 10 64-bit, NTFS.

`datatable` version:
```
dt.build_info

namespace(version='0.11.0',
          build_date='2020-09-19 16:54:54',
          git_revision='99168c09b73b2f4ecdf4bf17af3db64dc18ca85a',
          git_branch='HEAD',
          git_date='2020-09-19 16:32:35',
          git_diff='')
```

Happy to provide additional info as needed.

Some initial googling suggested this error appears on FAT partitions (4GB filesize limit), which is not applicable in my case...

PS: Thanks for `datatable`, much appreciated!

**Comment by st-pasha** [comment] 2020-11-24 17:16
This is a duplicate of #2725, we're already working on resolving this problem.

**Closed by st-pasha** 2020-11-24 17:16 UTC
