### ISSUE TITLE
datatable install with apple m1

### ISSUE THREAD

**Issue by ztsweet** [h2oai/datatable#2912] opened 2021-03-28 01:56 UTC
ERROR: Command errored out with exit status 1:
     command: /Users/sweetsummers/opt/miniconda3/envs/pytorch/bin/python /Users/sweetsummers/opt/miniconda3/envs/pytorch/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/tmpd6bf9acy
         cwd: /private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-install-6y_4f6u_/datatable_9f19488ae57c439dbc632092ab460c81
    Complete output (2 lines):
    Command `git rev-parse HEAD` failed with code 128: fatal: not a git repository (or any of the parent directories): .git
------------------------------------------
ERROR: Command errored out with exit status 1:
   command: /Users/sweetsummers/opt/miniconda3/envs/pytorch/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-install-6y_4f6u_/datatable_21b822b936a4410592fe70364972f6a4/setup.py'"'"'; __file__='"'"'/private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-install-6y_4f6u_/datatable_21b822b936a4410592fe70364972f6a4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-wheel-3u1ialoz
       cwd: /private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-install-6y_4f6u_/datatable_21b822b936a4410592fe70364972f6a4/
  Complete output (77 lines):
  
  Start setup.py
    command = `bdist_wheel`
    setuptools version = 52.0.0.post20210125
  
  Find an LLVM installation
    Environment variable LLVM is not set
    Environment variable LLVM7 is not set
    Environment variable LLVM6 is not set
    Environment variable LLVM5 is not set
    Environment variable LLVM4 is not set
    Candidate directory `/usr/local/opt/llvm` not found
    The build will proceed without Llvm support
  
  Determine the compiler
    Environment variable `CXX` is not set
    Environment variable `CC` is not set
    Llvm installation not found, cannot search for the clang++ compiler
    distutils.ccompiler reports the default compiler to be `cc`
    Compiler `clang++` will be used
    clang++ --version :
      Apple clang version 12.0.0 (clang-1200.0.32.28)
      Target: x86_64-apple-darwin20.2.0
      Thread model: posix
      InstalledDir: /Library/Developer/CommandLineTools/usr/bin
  
  Prepare the environment
    CC = clang++
    CXX = clang++
    LDFLAGS = -L/opt/homebrew/opt/icu4c/lib
    ARCHFLAGS = -m64
    LLVM_CONFIG =
    MACOSX_DEPLOYMENT_TARGET = 10.13
  
  Find compile include directories
    `c` is the main C++ source directory
    `/Users/sweetsummers/opt/miniconda3/envs/pytorch/include/python3.9` added from CONFINCLUDEPY
  
  Determine the extra compiler flags
    -std=c++11
    -stdlib=libc++
    -Ic
    -fPIC
    -g2
    -O3
    -Weverything
    -Wno-c++98-compat-pedantic
    -Wno-c99-extensions
    -Wno-exit-time-destructors
    -Wno-float-equal
    -Wno-global-constructors
    -Wno-reserved-id-macro
    -Wno-switch-enum
    -Wno-weak-template-vtables
    -Wno-weak-vtables
    -I/Users/sweetsummers/opt/miniconda3/envs/pytorch/include/python3.9
    -isystem /Users/sweetsummers/opt/miniconda3/envs/pytorch/include/python3.9
    -Ic
  
  libc++.1.dylib :::: 1 ::::
  Find the required dynamic libraries
  
  Determine the extra linker flags
  
  
  SystemExit: `locate` command returned the following error while looking for libc++.1.dylib:
  
  WARNING: The locate database (/var/db/locate.database) does not exist.
  To create the database, run the following command:
  
    sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
  
  Please be aware that the database can take some time to generate; once
  the database has been created, this message will no longer appear.
  
  
  
  ----------------------------------------
  ERROR: Failed building wheel for datatable
----------------------------------------
ERROR: Command errored out with exit status 1:
     command: /Users/sweetsummers/opt/miniconda3/envs/pytorch/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-install-6y_4f6u_/datatable_21b822b936a4410592fe70364972f6a4/setup.py'"'"'; __file__='"'"'/private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-install-6y_4f6u_/datatable_21b822b936a4410592fe70364972f6a4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-record-ialg8o69/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sweetsummers/opt/miniconda3/envs/pytorch/include/python3.9/datatable
         cwd: /private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-install-6y_4f6u_/datatable_21b822b936a4410592fe70364972f6a4/
    Complete output (77 lines):
    
    Start setup.py
      command = `install`
      setuptools version = 52.0.0.post20210125
    
    Find an LLVM installation
      Environment variable LLVM is not set
      Environment variable LLVM7 is not set
      Environment variable LLVM6 is not set
      Environment variable LLVM5 is not set
      Environment variable LLVM4 is not set
      Candidate directory `/usr/local/opt/llvm` not found
      The build will proceed without Llvm support
    
    Determine the compiler
      Environment variable `CXX` is not set
      Environment variable `CC` is not set
      Llvm installation not found, cannot search for the clang++ compiler
      distutils.ccompiler reports the default compiler to be `cc`
      Compiler `clang++` will be used
      clang++ --version :
        Apple clang version 12.0.0 (clang-1200.0.32.28)
        Target: x86_64-apple-darwin20.2.0
        Thread model: posix
        InstalledDir: /Library/Developer/CommandLineTools/usr/bin
    
    Prepare the environment
      CC = clang++
      CXX = clang++
      LDFLAGS = -L/opt/homebrew/opt/icu4c/lib
      ARCHFLAGS = -m64
      LLVM_CONFIG =
      MACOSX_DEPLOYMENT_TARGET = 10.13
    
    Find compile include directories
      `c` is the main C++ source directory
      `/Users/sweetsummers/opt/miniconda3/envs/pytorch/include/python3.9` added from CONFINCLUDEPY
    
    Determine the extra compiler flags
      -std=c++11
      -stdlib=libc++
      -Ic
      -fPIC
      -g2
      -O3
      -Weverything
      -Wno-c++98-compat-pedantic
      -Wno-c99-extensions
      -Wno-exit-time-destructors
      -Wno-float-equal
      -Wno-global-constructors
      -Wno-reserved-id-macro
      -Wno-switch-enum
      -Wno-weak-template-vtables
      -Wno-weak-vtables
      -I/Users/sweetsummers/opt/miniconda3/envs/pytorch/include/python3.9
      -isystem /Users/sweetsummers/opt/miniconda3/envs/pytorch/include/python3.9
      -Ic
    
    libc++.1.dylib :::: 1 ::::
    Find the required dynamic libraries
    
    Determine the extra linker flags
    
    
    SystemExit: `locate` command returned the following error while looking for libc++.1.dylib:
    
    WARNING: The locate database (/var/db/locate.database) does not exist.
    To create the database, run the following command:
    
      sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
    
    Please be aware that the database can take some time to generate; once
    the database has been created, this message will no longer appear.
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sweetsummers/opt/miniconda3/envs/pytorch/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-install-6y_4f6u_/datatable_21b822b936a4410592fe70364972f6a4/setup.py'"'"'; __file__='"'"'/private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-install-6y_4f6u_/datatable_21b822b936a4410592fe70364972f6a4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/95/k2ztt39975n3vgby3mh3l13h0000gn/T/pip-record-ialg8o69/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sweetsummers/opt/miniconda3/envs/pytorch/include/python3.9/datatable Check the logs for full command output.

**Comment by Peter-Pasta** [comment] 2021-03-28 08:36
Not sure if this is the problem but I believe the highest Python version that can be used right now with datatable is 3.8.x. Maybe its worth giving it a try.

**Comment by ztsweet** [comment] 2021-03-28 11:21
my python version is 3.9.2,but it does't work

**Comment by Peter-Pasta** [comment] 2021-03-28 11:22
Exactly. You should try with 3.8.x

**Comment by ztsweet** [comment] 2021-03-28 11:50
it is my carelessness,thank you for your&nbsp;&nbsp;patience！



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 28, 2021 19:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [h2oai/datatable] datatable install with apple m1 (#2912)




 
Exactly. You should try with 3.8.x

**Comment by Peter-Pasta** [comment] 2021-03-28 14:36
So it worked? I am happy I was able to help you :)
I wish you the best.

**Comment by samukweku** [comment] 2021-03-28 20:09
@Peter-Pasta thanks for the resolution. @ztsweet if your challenge has been resolved, kindly close this issue.

**Comment by st-pasha** [comment] 2021-03-28 21:16
Duplicate of #2846

**Closed** 2021-03-28 21:16 UTC
Labels: duplicate
