### ISSUE TITLE
Performance of `.key`

### ISSUE THREAD

**Issue by nankaimy** [h2oai/datatable#3359] opened 2022-09-26 10:21 UTC
```python
# Input
import datatable as dt

df1 = dt.Frame(A=[1, 2, 3, 4], B=["a", "b", "c", "d"], D=[1, 2, 3, 4])
df2 = dt.Frame(A=[1, 2, 4, 5],
               B=["a", "b", "d", "e"],
               C=["a2", "b2", "d2", "e2"])

# Solution
df2.key = ["A", "B"]
output = df1[:, :, dt.join(df2)]
```

When join it must set .key first, when df  is very big, it will cost much time, does it exist another method?

**Comment by samukweku** [comment] 2022-09-26 11:41
@nankaimy at the moment keys have to be set before joining. How much time does setting the key cost, compared to the actual join?

**Comment by oleksiyskononenko** [comment] 2022-09-26 19:40
Duplicate of #3329

**Closed** 2022-10-04 06:08 UTC
Labels: duplicate
