### ISSUE TITLE
[bug] Compiling error on aarch64

### ISSUE THREAD

**Issue by frederikdyrmose** [h2oai/datatable#3468] opened 2023-05-29 21:45 UTC
- Did you find a bug in datatable, or maybe the bug found you?
I have developed a compact program which uses the datatable library for its operations. In my local development environment, the program works as expected. However, I'm encountering an issue when preparing for deployment: I cannot successfully install the datatable library on my server, which runs on an aarch64 architecture. 

- How to reproduce the bug?
```
pip install git+https://github.com/h2oai/datatable
```
I get the error:
```
#10 210.3       +==== ERRORS & WARNINGS ========
#10 210.3       |
#10 210.3       | gcc: error: unrecognized command-line option ‘-m64’
#10 210.3       |
#10 210.3       +===============================
#10 210.3       Error linking `src/datatable/lib/_datatable.cpython-311-aarch64-linux-gnu.so`
#10 210.3
#10 210.3       [end of output]
```

- Your environment?
I'm trying to install newest datatable version, inside the newest python docker image on an aarch64 machine.

**Comment by frederikdyrmose** [comment] 2023-05-29 22:13
Install and runs without any problems after commenting out the the following line in the file "ci/ext.py":
```
ext.compiler.add_linker_flag("-m64")
```

**Comment by oleksiyskononenko** [comment] 2023-05-30 05:50
Thanks for reporting. This issue will be addressed shortly.

Duplicate of #3430

**Closed by oleksiyskononenko** 2023-05-30 05:50 UTC
